// gui/src/components/layout/TopBar.tsx
import React, { useEffect, useState, useRef } from 'react';
import { Play, Square, Settings, LogOut, Grid3X3, Code, SplitSquareHorizontal, HelpCircle } from 'lucide-react';
import { useLinkClock } from '../../hooks/useLinkClock';
import { useStore } from '@nanostores/react';
import { playbackStore } from '../../stores/scene/sceneUI';
import { SplitToggleButton } from '../ui/SplitToggleButton';
import { layoutStore } from '../../stores/ui/preferences';

interface TopBarProps {
  isConnected: boolean;
  onConnect: () => void;
  onDisconnect: () => void;
  onToggleOptions: () => void;
  client: any;
  optionsPanelPosition?: 'left' | 'right' | 'bottom';
  onChangeOptionsPanelPosition?: (position: 'left' | 'right' | 'bottom') => void;
  currentView: 'editor' | 'grid' | 'split';
  onViewChange: (view: 'editor' | 'grid' | 'split') => void;
  isHelpOpen?: boolean;
  onToggleHelp?: () => void;
}

export const TopBar: React.FC<TopBarProps> = ({
  isConnected,
  onConnect,
  onDisconnect,
  onToggleOptions,
  client,
  currentView,
  onViewChange,
  isHelpOpen,
  onToggleHelp
}) => {
  const playback = useStore(playbackStore);
  const isPlaying = playback.isPlaying;
  const layout = useStore(layoutStore);
  const { phase, quantum } = useLinkClock(isPlaying);
  const tempo = playback.clockState[0] || 120;

  const [isEditingTempo, setIsEditingTempo] = useState(false);
  const [tempoInput, setTempoInput] = useState('');
  const tempoInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (isEditingTempo && tempoInputRef.current) {
      tempoInputRef.current.focus();
      tempoInputRef.current.select();
    }
  }, [isEditingTempo]);

  const handlePlay = async () => {
    try {
      await client.sendMessage({ TransportStart: "Immediate" });
    } catch (error) {
      console.error('Failed to send TransportStart:', error);
    }
  };

  const handleStop = async () => {
    try {
      await client.sendMessage({ TransportStop: "Immediate" });
    } catch (error) {
      console.error('Failed to send TransportStop:', error);
    }
  };

  const handleTempoDoubleClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    setIsEditingTempo(true);
    setTempoInput(tempo.toFixed(0));
  };

  const handleTempoKeyDown = (e: React.KeyboardEvent) => {
    e.stopPropagation();

    if (e.key === 'Enter') {
      handleTempoSubmit();
    } else if (e.key === 'Escape') {
      setIsEditingTempo(false);
    }
  };

  const handleTempoSubmit = async () => {
    if (!client || !isEditingTempo) return;
    setIsEditingTempo(false);

    const newTempo = parseFloat(tempoInput);
    if (isNaN(newTempo) || newTempo < 20 || newTempo > 999) return;

    try {
      await client.sendMessage({ SetTempo: [newTempo, "Immediate"] });
    } catch (error) {
      console.error('Failed to set tempo:', error);
    }
  };

  const handleTempoBlur = () => {
    if (isEditingTempo) {
      handleTempoSubmit();
    }
  };

  return (
    <div className="h-12 border-b" style={{ backgroundColor: 'var(--color-surface)', borderColor: 'var(--color-border)' }}>
      <div className="flex items-center justify-between px-4 h-full">
        <div className="flex items-center space-x-4">
          <h1 className="text-lg font-semibold" style={{ color: 'var(--color-text)', fontFamily: 'inherit !important' }}>
            Sova
          </h1>
          
          {/* View switching buttons */}
          {isConnected && (
            <div className="flex items-center border-2" style={{ borderColor: 'var(--color-border)' }}>
              <button
                onClick={() => onViewChange('editor')}
                className="p-2 transition-all"
                style={{ 
                  backgroundColor: currentView === 'editor' ? 'var(--color-primary)' : 'transparent',
                  color: currentView === 'editor' ? 'white' : 'var(--color-text)'
                }}
                title="Editor only"
              >
                <Code size={16} />
              </button>
              <button
                onClick={() => onViewChange('split')}
                className="p-2 border-x-2 transition-all"
                style={{ 
                  backgroundColor: currentView === 'split' ? 'var(--color-primary)' : 'transparent',
                  color: currentView === 'split' ? 'white' : 'var(--color-text)',
                  borderColor: 'var(--color-border)'
                }}
                title="Split view"
              >
                <SplitSquareHorizontal size={16} />
              </button>
              <button
                onClick={() => onViewChange('grid')}
                className="p-2 transition-all"
                style={{ 
                  backgroundColor: currentView === 'grid' ? 'var(--color-primary)' : 'transparent',
                  color: currentView === 'grid' ? 'white' : 'var(--color-text)'
                }}
                title="Grid only"
              >
                <Grid3X3 size={16} />
              </button>
            </div>
          )}
          
          {/* Split orientation toggle - only shown in split view */}
          {isConnected && currentView === 'split' && (
            <SplitToggleButton 
              orientation={layout.splitOrientation}
              className="border-2" 
              style={{ borderColor: 'var(--color-border)', color: 'var(--color-text)' }}
            />
          )}
        </div>
        
        <div className="flex items-center space-x-3">
          {isConnected && (
            <>
              <button
                onClick={handlePlay}
                className="p-2 border-2 transition-all"
                style={{ 
                  borderColor: isPlaying ? 'var(--color-success)' : 'var(--color-border)',
                  backgroundColor: isPlaying ? 'var(--color-success)' : 'transparent',
                  color: isPlaying ? 'white' : 'var(--color-text)'
                }}
                title="Start playback"
              >
                <Play size={16} fill={isPlaying ? 'white' : 'none'} />
              </button>
              <button
                onClick={handleStop}
                className="p-2 border-2 transition-all"
                style={{ 
                  borderColor: !isPlaying ? 'var(--color-error)' : 'var(--color-border)',
                  backgroundColor: !isPlaying ? 'var(--color-error)' : 'transparent',
                  color: !isPlaying ? 'white' : 'var(--color-text)'
                }}
                title="Stop playback"
              >
                <Square size={16} fill={!isPlaying ? 'white' : 'none'} />
              </button>
              <div
                className="w-40 h-6 overflow-hidden relative border select-none cursor-pointer"
                style={{
                  backgroundColor: 'var(--color-background)',
                  borderColor: isPlaying ? 'var(--color-success)' : 'var(--color-error)'
                }}
                onDoubleClick={!isEditingTempo ? handleTempoDoubleClick : undefined}
                title={isEditingTempo ? 'Enter BPM (20-999)' : 'Double-click to edit tempo'}
              >
                <div 
                  className="h-full transition-colors duration-300"
                  style={{ 
                    width: `${Math.max(0, Math.min(100, (phase / quantum) * 100))}%`,
                    backgroundColor: isPlaying ? 'var(--color-success)' : 'var(--color-error)'
                  }}
                />

                {/* Tempo input or display */}
                {isEditingTempo ? (
                  <input
                    ref={tempoInputRef}
                    type="number"
                    min="20"
                    max="999"
                    step="1"
                    value={tempoInput}
                    onChange={(e) => setTempoInput(e.target.value)}
                    onKeyDown={handleTempoKeyDown}
                    onBlur={handleTempoBlur}
                    onClick={(e) => e.stopPropagation()}
                    onMouseDown={(e) => e.stopPropagation()}
                    onMouseMove={(e) => e.stopPropagation()}
                    className="absolute inset-0 text-xs font-bold text-center bg-transparent border-0 outline-none"
                    style={{
                      color: 'var(--color-text)',
                      fontFamily: 'inherit',
                      pointerEvents: 'auto'
                    }}
                    autoFocus
                  />
                ) : (
                  <div className="absolute inset-0 flex items-center justify-center text-xs font-bold pointer-events-none" style={{
                    color: 'var(--color-text)',
                    textShadow: '0 0 2px rgba(0,0,0,0.5)',
                    fontFamily: 'inherit'
                  }}>
                    {isPlaying ? '▶' : '■'} | {tempo.toFixed(0)} BPM
                  </div>
                )}
              </div>
            </>
          )}
          
          <button
            onClick={onToggleHelp}
            className="p-2 border-2 transition-all hover:opacity-80"
            style={{ 
              borderColor: isHelpOpen ? 'var(--color-primary)' : 'var(--color-border)',
              backgroundColor: isHelpOpen ? 'var(--color-primary)' : 'transparent',
              color: isHelpOpen ? 'white' : 'var(--color-text)'
            }}
            title="Help"
          >
            <HelpCircle size={16} />
          </button>
          
          <button
            onClick={onToggleOptions}
            className="p-2 border-2 transition-all hover:opacity-80"
            style={{ 
              borderColor: 'var(--color-border)',
              backgroundColor: 'transparent',
              color: 'var(--color-text)'
            }}
            title="Options"
          >
            <Settings size={16} />
          </button>
          
          {isConnected ? (
            <button
              onClick={onDisconnect}
              className="p-2 transition-all hover:opacity-80"
              style={{ 
                color: 'var(--color-error)'
              }}
              title="Disconnect from server"
            >
              <LogOut size={16} />
            </button>
          ) : (
            <button
              onClick={onConnect}
              className="px-3 py-1.5 text-white text-sm transition-colors hover:opacity-90"
              style={{ backgroundColor: 'var(--color-primary)', fontFamily: 'inherit' }}
              title="Connect to server"
            >
              Connect
            </button>
          )}
        </div>
      </div>
    </div>
  );
};

// gui/src/lib/components/TopBar.svelte
<script lang="ts">
  import { Play, Pause, LogOut, Plus } from 'lucide-svelte';
  import { isConnected } from '$lib/stores/connectionState';
  import { isPlaying, clockState } from '$lib/stores/transport';
  import { startTransport, stopTransport, setTempo } from '$lib/api/client';
  import { invoke } from '@tauri-apps/api/core';
  import { paneLayout } from '$lib/stores/paneState';

  let isEditingTempo = $state(false);
  let tempTempoValue = $state('120');
  let tempoInputElement: HTMLInputElement;

  let barProgress = $derived(
    $clockState !== null
      ? (($clockState.beat % $clockState.quantum) / $clockState.quantum) * 100
      : 0
  );

  function handleAddPane() {
    paneLayout.addPane();
  }

  async function handleDisconnect() {
    try {
      await invoke('disconnect_client');
      isConnected.set(false);
    } catch (error) {
      // Disconnect failed - connection likely already closed
    }
  }

  function startEditingTempo() {
    if ($clockState !== null) {
      tempTempoValue = Math.round($clockState.tempo).toString();
      isEditingTempo = true;
      // Focus input after it's rendered
      setTimeout(() => tempoInputElement?.select(), 0);
    }
  }

  function cancelEditingTempo() {
    isEditingTempo = false;
  }

  async function saveTempoEdit() {
    const tempo = parseFloat(tempTempoValue);

    // Validate tempo (typically 30-300 BPM)
    if (isNaN(tempo) || tempo < 30 || tempo > 300) {
      cancelEditingTempo();
      return;
    }

    try {
      await setTempo(tempo);
      isEditingTempo = false;
    } catch (error) {
      console.error('Failed to set tempo:', error);
      cancelEditingTempo();
    }
  }

  function handleTempoKeydown(event: KeyboardEvent) {
    if (event.key === 'Enter') {
      event.preventDefault();
      saveTempoEdit();
    } else if (event.key === 'Escape') {
      event.preventDefault();
      cancelEditingTempo();
    }
  }
</script>

<div class="topbar">
  <div class="left-section">
    <span class="app-name">Sova</span>

    {#if $isConnected}
      <div class="actions">
        <div class="bar-progress" class:playing={$isPlaying} style="width: {barProgress}%"></div>

        <button
          class="transport-button play-button"
          onclick={() => $isPlaying ? stopTransport() : startTransport()}>
          {#if $isPlaying}
            <Pause size={16} />
          {:else}
            <Play size={16} />
          {/if}
        </button>

        <span class="transport-info">
          {#if $clockState !== null}
            {$clockState.beat.toFixed(1)}
          {:else}
            --
          {/if}
        </span>

        {#if isEditingTempo}
          <input
            bind:this={tempoInputElement}
            bind:value={tempTempoValue}
            onkeydown={handleTempoKeydown}
            onblur={saveTempoEdit}
            class="tempo-input"
            type="number"
            min="30"
            max="300"
            step="1"
          />
          <span class="tempo-unit">BPM</span>
        {:else}
          <span
            class="transport-info tempo-clickable"
            onclick={startEditingTempo}
            onkeydown={(e) => e.key === 'Enter' && startEditingTempo()}
            role="button"
            tabindex="0">
            {$clockState !== null ? `${Math.round($clockState.tempo)} BPM` : '-- BPM'}
          </span>
        {/if}
      </div>
    {/if}
  </div>

  <div class="right-section">
    <button class="add-pane-btn" onclick={handleAddPane} title="Add new pane">
      <Plus size={16} />
    </button>
    {#if $isConnected}
      <button class="disconnect-button" onclick={handleDisconnect} title="Disconnect">
        <LogOut size={16} />
        <span class="disconnect-text">Disconnect</span>
      </button>
    {/if}
  </div>
</div>

<style>
  .topbar {
    width: 100%;
    height: 40px;
    box-sizing: border-box;
    background-color: var(--colors-background, #1e1e1e);
    border-bottom: 1px solid var(--colors-border, #333);
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 0 12px;
    gap: 8px;
    overflow: hidden;
  }

  .left-section {
    display: flex;
    align-items: center;
    gap: 8px;
    min-width: 0;
  }

  .right-section {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    flex-shrink: 0;
    gap: 8px;
  }

  .app-name {
    font-family: monospace;
    font-size: 13px;
    font-weight: 700;
    color: var(--colors-text, #fff);
    letter-spacing: 0.5px;
    padding: 0 8px;
  }

  .add-pane-btn {
    background: none;
    border: 1px solid var(--colors-border, #333);
    color: var(--colors-text-secondary, #888);
    padding: 6px 10px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
  }

  .add-pane-btn:hover {
    border-color: var(--colors-accent, #0e639c);
    color: var(--colors-text, #fff);
  }

  .actions {
    display: flex;
    gap: 6px;
    align-items: center;
    position: relative;
    overflow: hidden;
    min-width: 0;
  }

  .bar-progress {
    position: absolute;
    top: 0;
    left: 0;
    height: 100%;
    background: var(--colors-surface, #2d2d2d);
    opacity: 0.3;
    pointer-events: none;
    z-index: 0;
  }

  .bar-progress.playing {
    background: var(--colors-accent, #0e639c);
    opacity: 0.35;
  }

  .transport-info {
    font-family: monospace;
    font-size: 11px;
    font-weight: 500;
    color: var(--colors-text, #ddd);
    padding: 4px 6px;
    white-space: nowrap;
    position: relative;
    z-index: 1;
  }

  .tempo-clickable {
    cursor: pointer;
    transition: color 0.2s;
  }

  .tempo-clickable:hover {
    color: var(--colors-text, #fff);
  }

  .tempo-input {
    font-family: monospace;
    font-size: 11px;
    font-weight: 500;
    color: var(--colors-text, #fff);
    background-color: var(--colors-surface, #2d2d2d);
    border: 1px solid var(--colors-accent, #0e639c);
    padding: 4px 6px;
    width: 50px;
    text-align: right;
    position: relative;
    z-index: 1;
  }

  .tempo-input:focus {
    outline: none;
    border-color: var(--colors-accent, #0e639c);
  }

  .tempo-unit {
    font-family: monospace;
    font-size: 11px;
    font-weight: 500;
    color: var(--colors-text-secondary, #888);
    padding: 4px 2px 4px 0;
    position: relative;
    z-index: 1;
  }

  .transport-button {
    background: none;
    border: 1px solid var(--colors-border, #333);
    color: var(--colors-text, #fff);
    padding: 6px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.2s;
    position: relative;
    z-index: 1;
  }

  .transport-button:hover {
    border-color: var(--colors-accent, #0e639c);
    color: var(--colors-accent, #0e639c);
  }

  .play-button {
    border: none;
  }

  .play-button:hover {
    color: var(--colors-accent, #0e639c);
  }

  .disconnect-button {
    background: none;
    border: 1px solid var(--colors-border, #333);
    color: var(--colors-text-secondary, #888);
    padding: 6px 10px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 6px;
    transition: all 0.2s;
    position: relative;
    z-index: 1;
  }

  .disconnect-button:hover {
    border-color: var(--colors-accent, #0e639c);
    color: var(--colors-text, #fff);
  }

  .disconnect-text {
    font-family: monospace;
    font-size: 11px;
    font-weight: 500;
  }
</style>
